services:
  - name: web
    instance_size_slug: s-1vcpu-1gb
    http_port: 8000
    routes:
      - path: /
    git:
      repo: "https://github.com/iwootten/empty-django-app"
      branch: master
    build_command: ""
    run_command: "python manage.py migrate; gunicorn --worker-tmp-dir /dev/shm djempty.wsgi"
    envs:
    - key: APP_DOMAIN
      scope: RUN_TIME
      value: ${APP_DOMAIN}